spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/diarydb
    username: root
    password: mwdsqlnet4850!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.SQL: debug
