spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/diarydb
    username: root
    password: test1234@#
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data_int.sql
logging:
  level:
    org.hibernate.type.descriptor.sql: DEBUG
jwt:
  header: token
  issuer: prgrms
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  expiry-seconds: 60
