spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: test1234@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#  sql:
#    init:
#      schema-locations: classpath:sql/schema.sql
#      data-locations: classpath:sql/data.sql
#      platform: mysql
#      encoding: UTF-8
logging:
  level:
    org:
      hibernate:
        org.hibernate.type.descriptor.sql: DEBUG
jwt:
  header: Authorization
  issuer: developer
  client-secret: EENY5W0eegTf1naQB2eDeyCLl5kRS2b8xa5c4qLdS0hmVjtbvo8tOyhPMcAmtPuQ
  expiry-seconds: 60
